
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwqlxcvoohgaealqccbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3cWx4Y3Zvb2hnYWVhbHFjY2JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyOTE1NjQsImV4cCI6MjA1Nzg2NzU2NH0.wH9wzhQH00ABBPTI7SsF_RimeoDgtJ94RbN8wwOLt0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storageKey: 'tontinetamer-auth-token',
      storage: window.localStorage
    },
    global: {
      fetch: (url, options) => {
        console.log(`Supabase API request to: ${url}`);
        return fetch(url, options)
          .catch(error => {
            console.error('Supabase network error:', error);
            throw new Error('Network error. Unable to connect to authentication service. Please check your internet connection.');
          });
      }
    }
  }
);

// Helper function to check Supabase connection
export const checkSupabaseConnection = async (): Promise<boolean> => {
  try {
    const { error } = await supabase.auth.getSession();
    return !error;
  } catch (error) {
    console.error('Failed to connect to Supabase:', error);
    return false;
  }
};
